name: Linter

on:
  push:
    branches: [ * ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable