name: Release

on:
  workflow_dispatch:  # Allow manual triggering of the workflow


jobs:
  publish:
    runs-on:
      group: databrickslabs-protected-runner-group
      labels: linux-ubuntu-latest
    # if: ${{ github.ref_name == 'main' }}
    environment: release
    permissions:
      # Used to authenticate to PyPI via OIDC and sign the release's artifacts with sigstore-python.
      id-token: write
      # Used to attach signing artifacts to the published release.
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install hatch

      - name: Build dist
        working-directory: ./python
        run: make build-dist

      - name: Create tag
        id: create_tag
        run: |
          # Extract version from version.py
          VERSION=$(python -c "exec(open('./python/version.py').read()); print(__version__)")
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
          echo "Creating tag v${VERSION}"

          # Check if tag already exists
          if git rev-parse "v${VERSION}" >/dev/null 2>&1; then
            echo "Tag v${VERSION} already exists, skipping tag creation"
          else
            git tag -a "v${VERSION}" -m "Release version ${VERSION}"
            git push origin "v${VERSION}"
          fi

      - name: Draft release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.create_tag.outputs.VERSION }}
          draft: true
          files: |
            python/dist/dbl_tempo*.whl
            python/dist/tempo*.whl

      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: python/dist/

      - name: Sign artifacts with Sigstore
        uses: sigstore/gh-action-sigstore-python@v3.0.0
        with:
          inputs: |
            python/dist/dbl_tempo*.whl
            python/dist/tempo*.whl
          release-signing-artifacts: true
