name: release

on:
  push:
    # tags:
    #   - 'v*' # only release a versioned tag, such as v.X.Y.Z
    branches: ['*']

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # - uses: actions/cache@v2
      #   id: cache
      #   with:
      #     path: ~/.cache/pip
      #     key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
      #     restore-keys: |
      #       ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
      #       ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox

      - name: Build dist
        working-directory: ./python
        run: tox -e build-dist

      # - name: Publish a Python distribution to PyPI
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #   if: $${{ github.ref }} == 'refs/heads/master'
      #   with:
      #     user: __token__
      #     password: ${{ secrets.LABS_PYPI_TOKEN }}
      #     packages_dir: python/dist/
  
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # - uses: actions/cache@v2
      #   id: cache
      #   with:
      #     path: ~/.cache/pip
      #     key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
      #     restore-keys: |
      #       ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
      #       ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox

      - name: Build docs
        working-directory: ./python
        run: tox -e build-docs

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: html-docs
          path: docs/_build/html/

      # - name: Deploy 🚀
      #   uses: peaceiris/actions-gh-pages@v3
      #   if: $${{ github.ref }} == 'refs/heads/master'
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: docs/_build/html
